### ISSUE TITLE
Invalid Byte Sequence on settings/backup

### ISSUE THREAD

**Issue by xjmzx** [lumehq/lume#104]
Signed in with npub only. 
Seems to crash on selecting backup.
All other functions seem pretty stable.

lume version 2.0.1
macos 14.1.0 M1

**Comment by reyamir** [comment]
Yup, settings screen is broken now, I'm working on it

**Comment by xjmzx** [comment]
I'm sure there's much work to do. If there are helpful observations/bugs found, will let you know.
Great work from v1.
