### ISSUE TITLE
Cannot initialize database: "the `signature` field was not set on the updater response"

### ISSUE THREAD

**Issue by Sebastix** [lumehq/lume#106]
Just downloaded the latest version on my MacOS 14.0 device. I was using a earlier `v1` version of Lume.

```
Cannot initialize database: "the `signature` field was not set on the updater response"
```

https://shares.sebastix.dev/i2bELv79.png

After downloading the debug release, I was able to login and use the app.

**Comment by SwissArmyWrench** [comment]
Also experiencing this same issue on Windows 11 with the EN-US MSI. Will try again with the debug release.

**Comment by reyamir** [comment]
Hi, I notice some bug with the updater service, so you can try latest version (it will skip download new update step) https://github.com/luminous-devs/lume/releases/tag/v2.0.1
