### ISSUE TITLE
Title bar buttons not working on Windows 11

### ISSUE THREAD

**Issue by SwissArmyWrench** [lumehq/lume#107]
Potentially related to #74. I am not familiar enough with MacOS to know if this is the same bug or not.

On win11, the minimize, maximize/restore, and close buttons do not do anything. The close button turns red when hovered over, the other buttons do not do anything at all. Nothing happens upon clicking any of the buttons. 

However, when using keyboard shortcuts like `Alt + F4` or `Win + Up` the window behaves exactly as expected.

**Comment by reyamir** [comment]
Hi, thank for detail report, it isn't issue on macOS, maybe it only occur on Windows or Linux
I will look into it

**Comment by reyamir** [comment]
I've found the problem
next update will be released in next week 🔥
