### ISSUE TITLE
Problem with dark mode on mac os sonoma

### ISSUE THREAD

**Issue by eznix86** [lumehq/lume#108]
When importing a npub, the dark mode seems to break, we have white text on a gray area.

<img width="542" alt="Screenshot 2023-11-13 at 21 23 02" src="https://github.com/luminous-devs/lume/assets/26553194/896e0190-df25-437f-8bac-cade5319c382">

**Comment by reyamir** [comment]
Thank for your report, it will be fixed in the next update (this week)
