### ISSUE TITLE
Error when trying to message someone

### ISSUE THREAD

**Issue by karnagebitcoin** [lumehq/lume#109]
![CleanShot 2023-11-16 at 10 11 05@2x](https://github.com/luminous-devs/lume/assets/131526701/1453477b-990f-4adc-998a-93d6b9f03e89)

1. Hovered over name
2. Clicked Message
3. Got this error

**Comment by karnagebitcoin** [comment]
Clicking "reload app" doesn't do anything.

**Comment by reyamir** [comment]
I've released a dedicate app (NIP17) for direct message, https://github.com/lumehq/coop
lume will not have direct message
