### ISSUE TITLE
"Cannot read properites of null (reading 'useState')" error when launching the latest version.

### ISSUE THREAD

**Issue by SwissArmyWrench** [lumehq/lume#114]
I downloaded and installed the latest release from the standard MSI, not the debug one. Upon launching, I was greeted with this screen:

![image](https://github.com/luminous-devs/lume/assets/137639586/6c242306-e1ab-4e23-b36e-ae781f3501ab)

After relaunching lume, and then after that rebooting my computer, no change in behavior was seen.

Also, using the debug version MSI, I got the same thing.

**Comment by reyamir** [comment]
Hi, thank for your report, a lot of other windows users get same error with you. I'm working on hotfix for it

**Comment by reyamir** [comment]
Hi, I've released a new version to fix your issue: https://github.com/luminous-devs/lume/releases/tag/v2.1.2
