### ISSUE TITLE
Can't log out

### ISSUE THREAD

**Issue by tensor5g** [lumehq/lume#119]
The logout option doesn't appear to do anything for me

Windows 11 23H2

https://github.com/luminous-devs/lume/assets/74799905/5813e9ec-4384-4eb5-aa83-66c1ea7b68e4

I've got some other issues but I wanted to see if logout/login would fix them

**Comment by reyamir** [comment]
Hi, thank for your report
You can report all issues, I've a plan for new hotfix today

**Comment by reyamir** [comment]
Hi, I've fixed your issue in the latest release, can you help me try it https://github.com/luminous-devs/lume/releases/tag/v2.1.3

**Comment by tensor5g** [comment]
After installing the new version I have two new issues. I get this error during installation

![image](https://github.com/luminous-devs/lume/assets/74799905/4982b7ca-eb85-4935-be36-5dd00f3eaf5b)

Clicking OK the install seems to continue fine. After I launch Lume I noticed I was signed out so I put in my npub and tried to click "Continue with nsecBunker" but nothing happens

![image](https://github.com/luminous-devs/lume/assets/74799905/2e6f353d-2be7-4914-9bb5-d7c07148f0d7)

Restarting did not help

**Comment by reyamir** [comment]
oh, it strange, I will set up a Windows vm and test your issue

or you can delete lume's db at this location: C:\Users\<user name>\AppData\Roaming\com.lume.nu\ -> delete file lume_v2.db

then you can restart app

**Comment by reyamir** [comment]
Oh, I've found a problem with `login with nsecBunker`, I'm working to fix it
maybe I will release other hotfix today or tomorrow

if you get other issues, you can report it to me here. I'm fully spending this week just for fix bugs. sorry for buggy release

**Comment by tensor5g** [comment]
Ok, after signing in manually with nsec I get this error when opening my profile (clicking icon in bottom left)

![image](https://github.com/luminous-devs/lume/assets/74799905/226fdf4c-d33d-4f4e-a45f-d4edbcd50307)

**Comment by reyamir** [comment]
I'm working on it too

**Comment by reyamir** [comment]
Hi, I've released new version to fix your issue: https://github.com/luminous-devs/lume/releases/tag/v2.1.4

**Comment by tensor5g** [comment]
Getting same nip05 error when clicking my profile button. Confirmed I'm on 2.1.4

**Comment by reyamir** [comment]
oh, I will check again
can you share me your nip05, maybe something wrong when verify your nip05

**Comment by reyamir** [comment]
yup, I've found the issue, I'm working on new hotfix

**Comment by reyamir** [comment]
sorry for bothering you again, can you help me check this version https://github.com/luminous-devs/lume/releases/tag/v2.1.5
I've added the fallback if nip05 cannot be load

**Comment by tensor5g** [comment]
Thank you, I can load the profile now. Next issue is that I cannot seem to follow anyone. I hover over the button, it turns blue, but clicking it doesn't do anything.

**Comment by reyamir** [comment]
Hi, I've pushed new update again 😅, https://github.com/luminous-devs/lume/releases/tag/v2.1.6
You can update via "Check for update" button in Settings Screen -> About, or you can enable auto update

**Comment by tensor5g** [comment]
Clicking the follow button now causes my window to go white

![image](https://github.com/luminous-devs/lume/assets/74799905/1d162f54-d3fb-4444-b499-f0adc7f49fc7)


Also there is a console open whenever I open Lume

![image](https://github.com/luminous-devs/lume/assets/74799905/999f097d-b32f-42f0-a0e8-91efc20018df)

**Comment by reyamir** [comment]
Oh, look like this bug only occur on Windows, I will do more test on Windows today

**Comment by reyamir** [comment]
Hi, I've pushed new version to fix your issue https://github.com/luminous-devs/lume/releases/tag/v2.1.7
You can reinstall with version without `-debug` flag in name, it won't show console when open app

And can you share me your npub, you have great contribute to lume by raise a lot of issues from the last week
I'm working on new lume.nu website which have contributor page, and I will add you to it

**Comment by tensor5g** [comment]
The white window is fixed, thank you. I will DM you my npub.

Next issue, I seem to be getting duplicate notifications. I assume I am getting the same notification from each relay?

![image](https://github.com/luminous-devs/lume/assets/74799905/c36078c0-8425-4207-9a22-d3ba3cbe51de)

**Comment by reyamir** [comment]
Ah, it already have dedup function, but maybe a bug cause same event display multiple times or maybe it is spam replies. I will check it, and I also revamp this part to show reply content instead of your post content
