### ISSUE TITLE
[LUME-36] Beta 3 - Unable to upload new images to profile

### ISSUE THREAD

**Issue by zyrotin** [lumehq/lume#139]
When I tried to upload a background image, or change my profile picture I got this error-

![image](https://uploads.linear.app/95be30bb-de59-4292-83c8-b8d9142186db/cfba4dae-3fa0-4e96-ac66-5fd28839216f/1c553ee0-c45b-435c-b005-d1cc122dce2d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzk1YmUzMGJiLWRlNTktNDI5Mi04M2M4LWI4ZDkxNDIxODZkYi9jZmJhNGRhZS0zZmEwLTRlOTYtYWM2Ni01ZmQyODgzOTIxNmYvMWM1NTNlZTAtYzQ1Yi00MzVjLWIwMDUtZDFjYzEyMmRjZTJkIiwiaWF0IjoxNzA1MzY1ODMwLCJleHAiOjE3MDU0NTIyMzB9.k0PCA2w3ZcaAmTjDjhOAcyIr4JuTFVp6aaqmhgqqWsM)

<sub>From [SyncLinear.com](https://synclinear.com) | [LUME-36](https://linear.app/lume-nu/issue/LUME-36/beta-3-unable-to-upload-new-images-to-profile)</sub>

**Comment by prajna-pranab** [comment]
I was also unable to add a background image to my profile. No error message, it loaded the image but when it saved the profile the background image was reset to blank.
