### ISSUE TITLE
How to connect lume to custom local relay?

### ISSUE THREAD

**Issue by Nathy-bajo** [lumehq/lume#142]
Hi, I am trying to connect `lume` to my local relay `nostr-rs-relay`. 

But I get this error `URL is invalid, a relay must use websocket protocol (start with wss:// or ws://). Please check again` when my relay url is `wss://localhost/`. What is the issue please?

**Comment by reyamir** [comment]
Hi, thank for your report, this is a issue with relay validate function, it is mark localhost as invalid. I will update it

**Comment by Nathy-bajo** [comment]
Alright, thank you very much. 

(Great repo btw ❤️)
