### ISSUE TITLE
3.0 beta: how to view thread?

### ISSUE THREAD

**Issue by badonyx** [lumehq/lume#144]
I cannot find any way to view a thread and its comments in lume 3.0 beta. Am I missing something?

**Comment by reyamir** [comment]
Hi, thank for your report
You can click to this button to view certain thread 
<img width="403" alt="Screenshot 2024-01-24 at 07 13 27" src="https://github.com/luminous-devs/lume/assets/123083837/db7125c4-aab9-449e-959b-312294b6191b">

And `Pin` button to pin thread as a new column

I see this UX cause confuse for some users, I will redesign this part
