### ISSUE TITLE
Beta 3 - Cannot Log Out

### ISSUE THREAD

**Issue by zyrotin** [lumehq/lume#149]
No way to log out.
The menu that is supposed to be shown to let me log out does not come up.
Using Mac OS 14.2.1

https://github.com/luminous-devs/lume/assets/6876060/1a4ec4b3-5e26-451b-ab9b-9f9eb5a2d314

**Comment by reyamir** [comment]
Ah, look like you're using old build, can you help me remove install then reinstall with new build here https://github.com/luminous-devs/lume/releases/tag/v3.0.0

Sorry, I've mess up with Github Releases, so auto-updater isn't work in your case 😅

I'll build a new updater without rely on Github Releases

**Comment by zyrotin** [comment]
Awesome. Thanks! Got it downloaded and running :)
