### ISSUE TITLE
Spread syntax requires ...iterable[Symbol.iterator] to be a function

### ISSUE THREAD

**Issue by karnagebitcoin** [lumehq/lume#152]
Just encountered this. Not sure what I was doing, but reporting regardless.

**Comment by reyamir** [comment]
oh, can you help me check new update in Settings Screen 
<img width="1011" alt="image" src="https://github.com/luminous-devs/lume/assets/123083837/a9360f94-d8e6-47ee-bc84-f152b431e6f4">

I've mess up with updater server, some old build cannot auto upgrade to new, so make sure you're using new build

**Comment by karnagebitcoin** [comment]
Just noticed there's no way to change email that already exists with nsec bunker path

![CleanShot 2024-01-30 at 12 16 46@2x](https://github.com/luminous-devs/lume/assets/131526701/a741039d-ab6f-4a21-a5ab-9b7e95f29f65)

I can't click the input to change, have to restart the process.

**Comment by reyamir** [comment]
Yup, some functions still missing in nsecbunker

In Lume side, I will add "beta" badge when user choose "Manage by Provider" method and note "Some functions still missing or not work as expected, you should not create your main account with this method" to clarify it with user

But honesly, I think this is a mistake to add this method at this time, it creating too much issue 😅
