### ISSUE TITLE
Can't resize window

### ISSUE THREAD

**Issue by HonkMonster** [lumehq/lume#164]
I believe I was able to do this in 3.0.0 or earlier, but I can no longer resize the window by dragging the corners. I also don't get the Windows 11 snap menu by hovering over the maximize option. Maximize still does work though.

Expected:
![image](https://github.com/lumehq/lume/assets/153048038/d00a76fa-e39f-4f1d-8af2-f602cc9c481f)

Actual:
![image](https://github.com/lumehq/lume/assets/153048038/57dde568-fdfe-43e8-99f2-4f24d4bc7797)

**Comment by reyamir** [comment]
oh, thank for your report
look like custom titlebar doesn't work well on windows, I will dig more into it

**Comment by prajna-pranab** [comment]
I have a similar problem in Linux Mint. There are only minimise and close buttons, no full screen button. Also I can't see the bottom of the window and can't drag the top of the window down to then drag the window up. In the settings screen I changed my profile background but it doesn't stick when I move away from the profile settings (maybe there is an accept button at the bottom of the window that I can't see). I can make the window wider or narrower by dragging the edge but can't drag the top and can't see the bottom (it's hidden behind the task bar).

**Comment by reyamir** [comment]
oh, thank for your report, I will set up linux mint and test it
