### ISSUE TITLE
Loading Spinner Offset

### ISSUE THREAD

**Issue by orangesurf** [lumehq/lume#168]
The loading spinner seems offset, causing a wobble.

The [loading icon](https://github.com/lumehq/lume/blob/9753e6d6b4097c8302d7645b330795f55555a09b/packages/icons/src/loader.tsx#L4) I could find looked ok, but doesn't match the one in with the wobble.

https://github.com/lumehq/lume/assets/91332210/752c228d-d357-4edc-8fa0-e9ca92d416fd

**Comment by reyamir** [comment]
Yup, this is weird bug that I don't know how to fix 🤣
I just use tailwind `animate-spin` class for https://tailwindcss.com/docs/animation#spin

**Comment by reyamir** [comment]
Maybe I will create custom spinner

**Comment by reyamir** [comment]
Yo, this weird bug is fixed in the next update, I've added this spinner from radix https://www.radix-ui.com/themes/docs/components/spinner
