### ISSUE TITLE
Missing texts in the flatpak app

### ISSUE THREAD

**Issue by ademar111190** [lumehq/lume#176]
I just installed the Flatpak app and it seems some localizations are missing or for some reason not loaded correctly.

Look at the screenshot attached how instead of the texts it shows some kind of id which I believe is shown as some sort of fallback if the text is not loaded.

![Screenshot_20240408_095822](https://github.com/lumehq/lume/assets/1225438/2bcb1bac-f80c-4150-8d1b-a50292c98b8f)

**Comment by reyamir** [comment]
Thank for your report
I will migrate to https://weblate.org/en/ to better manage translation
