### ISSUE TITLE
Lume 3.0.0 crashing when clicking the "Pin" button on reposts.

### ISSUE THREAD

**Issue by mornec-ridhut** [lumehq/lume#177]
Hi,

Thanks for your work on Lume. I find this software to be the only Nostr client that's pleasant to use and I really appreciate the work you've put into it.

That said, I'm having some issues with Lume 3.0.0 intermittently crashing on me. I was able to trigger a crash by clicking the "Pin" on a repost note and it returned this error:

```
undefined is not an object (evaluating 'n.pubkey')
```

I'm also having this issue in 3.0.1 along with a general slowness when loading feeds on the program. I've reverted back to 3.0.0 since it seems to be stable for my system. Let me know if there's anything that I can do to help you better diagnose this issue.

**Comment by reyamir** [comment]
Hi, thank for your report, I will push an hotfix for v3 to fix your issue

**Comment by mornec-ridhut** [comment]
Looks like this is working properly now.

**Comment by reyamir** [comment]
Yo, I'm happy it's worked well now
