### ISSUE TITLE
Lume crashes when viewing a thread.

### ISSUE THREAD

**Issue by davidjj999** [lumehq/lume#179]
Using Lume 3.0 flatpak on Fedora 39.  

There are some threads in my timeline where the original post is displayed as 'unable to fetch event'.  If I click view thread the client crashes with the error:  undefined is not an object (evaluating 'n.pubkey')

Please let me know if there is any more information I can provide to help

![image](https://github.com/lumehq/lume/assets/54918535/786ef731-ff2a-402f-bd12-c2bc6d6f09d5)

**Comment by reyamir** [comment]
Oh, same error with #177, I'm working on bugfix, it will release on later today

**Comment by reyamir** [comment]
Hi, I've pushed v3.0.2 to fixed your issue, can you help me update and test it?

**Comment by davidjj999** [comment]
I installed v3.0.2 rpm and this crash no longer happens.  Recommend close this issue.  Thanks for the quick update, I really like this app and am looking forward to 4.0!

**Comment by davidjj999** [comment]
Crash no longer happens on 3.0.2 rpm
