### ISSUE TITLE
Crash when trying to launch on x64 build v4.0.7 (and also v4.0.6)

### ISSUE THREAD

**Issue by lingmann** [lumehq/lume#197]
The 4.0.6 and 4.0.7 x64/amd64 builds crash when trying to connect with my Nostr profile. The app spins for roughly 1 minute after I launch and click on my profile button. Connecting to a newly generated test nostr account works fine. This is the first time I'm using the app, so this should be a pretty clean install as well.

Here is the repro:

- Profile was configured using a Nostr Connect bunker URI.
- I have quite a few [NIP65 mailboxes](https://njump.me/npub1rf9g77w2uzteagu9ck9tn725lkkv6meyteh6gag2084h2y9ww48qlmdtwe) configured on the profile I'm using, so likely related?

LMK if there are any other debugging or diagnostic details that would be useful to share. Happy to do so.

**Comment by reyamir** [comment]
Hi, thank for trying Lume.
I've found the problem cause your issue, I'll push new hotfix today

**Comment by reyamir** [comment]
Hi, sorry for the delay
I've pushed new update https://github.com/lumehq/lume/releases/tag/v4.0.8 to address the issue related to nostr connect.

**Comment by lingmann** [comment]
No worries, and thanks for the quick investigation and follow-up. I just tested with v4.0.8 and it was crashing again... but once I cleared out my saved account (removed the nostr_secret entry from OSX Keychain) and then re-established the bunker connection it is now working! 🥳

Cheers :)
