### ISSUE TITLE
Crashing on Launch

### ISSUE THREAD

**Issue by macos-node** [lumehq/lume#228]
Tried changing relays for bootstrapping.
Can't seem to get Lume to start since upgrade to latest.

Please see the error log/crash report

[Lume Crash Report M1 macOS](https://cdn.satellite.earth/b9fe2e8fb36fcb262272d92d6768e6b4eb2b1a3f1fe8b5e21592ad80ae8583a2.txt)

**Comment by reyamir** [comment]
I've found a bug with the update bootstrap relay function. New update will be on air on tomorrow.

**Comment by reyamir** [comment]
Sorry for later reply, this bug fix included in the next major version, so I will release it later than expect.

**Comment by xjmzx** [comment]
> Sorry for later reply, this bug fix included in the next major version, so I will release it later than expect.

That's great news. I love testing it, and seing this application evolve.

**Comment by reyamir** [comment]
Hi, this issue is fixed in latest release, if you still got error, feel free reopen the issue.
