### ISSUE TITLE
[IDEA] Distribution by flatpak

### ISSUE THREAD

**Issue by victorffrock** [lumehq/lume#43]
Hey, what do you think about distributing the linux version via flatpak? It's easier to debug, develop and more convenient to distribute. And for the user it's better because it's a universal format and easy to update.

**Comment by reyamir** [comment]
It already on my plan but postpone it due to I don't have any device for carefully tested and fix UI for Linux as well as Windows. Currently, distribution for linux and windows make by github actions

**Comment by reyamir** [comment]
me too, I'm Vietnamese 😁

**Comment by stpnwf** [comment]
Same here. If you need testers, I am available.

**Comment by marek22k** [comment]
I would also be happy to see a release on Flathub.

**Comment by stpnwf** [comment]
Hoping a Flathub release comes soon!

**Comment by reyamir** [comment]
I've tried build flatpak version, but failed 😅. Look like we need to wait Tauri release official support for flatpak https://github.com/tauri-apps/tauri/issues/3619

I'm also publish a bounty for flatpak: https://nostrbounties.com/b/naddr1qq9rzd3ex5cnjwpe8ycsygqjvypmlhwgmujkkms2hltlx7tusrwvf65g7lp0slw5zppzpdxktupsgqqqw4rs5pgcdk

**Comment by getoffghub** [comment]
FYI: [Cinny desktop](https://github.com/cinnyapp/cinny-desktop) is a Matrix client made with Tauri and it is on Flathub. [Here's](https://github.com/flathub/in.cinny.Cinny) the manifest.

**Comment by reyamir** [comment]
> FYI: [Cinny desktop](https://github.com/cinnyapp/cinny-desktop) is a Matrix client made with Tauri and it is on Flathub. [Here's](https://github.com/flathub/in.cinny.Cinny) the manifest.

I will look into it 🔥

**Comment by ajz3d** [comment]
So are there any news about the progress in making the Flathub build?

**Comment by reyamir** [comment]
Hi, you can download the flatpak build here: https://github.com/luminous-devs/lume/releases/download/v3.0.0/lume_3.0.0_amd64.flatpak

Known issues:
- I've found a bug in flatpak build that prevent you store privkey, so signer isn't working. I've fixed this issue but in new build only, I will deliver new build this week.

**Comment by RasheedAZ** [comment]
Thanks for the Flatpak. Any chance of having a verified listing on Flathub?

**Comment by reyamir** [comment]
Oh, I didn't know about it, let me check their guideline for verify

**Comment by RasheedAZ** [comment]
Hi. Any news about Flathub listing? Thanks :)

**Comment by reyamir** [comment]
Hi, I've checked the flathub document for listing, it's not hard, I will do it for upcoming v4 release. Beside the main app, I will build another native version - called Lume Mini for Linux based on GTK4 and Libadwaita, which also distributed via flatpak by default
