### ISSUE TITLE
ubuntu deb failed to install

### ISSUE THREAD

**Issue by reyamir** [lumehq/lume#44]
Installed .deb on ubuntu 22. it is giving:
lume: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by G-R-A-F-F** [comment]
Same here.

**Comment by som-cs** [comment]
This fixes it (a problem with packaging in 22.04):

`$ wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb`

`$ sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb`

**Comment by reyamir** [comment]
wow, thank you
I'll try embed it to package

**Comment by reyamir** [comment]
v1.2.2 is fixed this issue, https://github.com/luminous-devs/lume/releases/tag/v1.2.2
