### ISSUE TITLE
Appimage not logging in.

### ISSUE THREAD

**Issue by RBauglir** [lumehq/lume#54]
I'm using Lume appimage in openSUSE Leap 15.5, and the app doesn't log in:

- If I generate new keys, the app asks me for a local password, to config the profile, a name for the "lume.nu" ID, it asks me to select 10 plebs (blindly because I cannot see what I'm selecting; image 1), it asks me to send a message saying I'm using Lume, and then rolls infinitely showing an "interesting fact" (image 2).
- If I use my pregenerated (with Lume) private key, the app asks me for a local password, it tells me about continuing with something I cannot see (image 3; maybe a Lume ID?) and, when I continue, it rolls infinitely saying "creating" (image 4).

In both above cases, if I close the app and reopen it, after asking me for the local password, it goes directly to the "interesting fact" screen and rolls infinitely again.

![Screenshot_20230717_013149](https://github.com/luminous-devs/lume/assets/44709730/9ef31142-a715-4073-90b9-0f36bf5d0842)
![Screenshot_20230717_013739](https://github.com/luminous-devs/lume/assets/44709730/ec2f2f5e-3f23-4d3a-9f8f-e557b2735211)
![Screenshot_20230717_013314](https://github.com/luminous-devs/lume/assets/44709730/2c1757be-24fe-47f8-99ad-ee1d4d991616)
![Screenshot_20230717_013342](https://github.com/luminous-devs/lume/assets/44709730/6ad3c4cc-3d9b-4b6d-a10b-e240aff68955)

**Comment by reyamir** [comment]
thank you for detail report, I will check it
look like some issue with relay connections

**Comment by TheSameCat2** [comment]
Same on OpenSuSE Tumbleweed
