### ISSUE TITLE
Columns don't have enough bottom padding to get to controls on last note

### ISSUE THREAD

**Issue by erskingardner** [lumehq/lume#63]
![image](https://github.com/luminous-devs/lume/assets/202880/8b28b909-cbcc-4906-a105-bccb02925770)

Noticed that if you're at the end of a column of notes it's not possible to scroll far enough to get to the icons to reply/like/zap etc

**Comment by reyamir** [comment]
thank for your report, I'll ship new version at the weekend which has major upgrade in UI 🔥

**Comment by prajna-pranab** [comment]
It seems this is still a problem running on Linux Mint.
