### ISSUE TITLE
Cannot resize window in macOS (x64)

### ISSUE THREAD

**Issue by kroucis** [lumehq/lume#71]
The window is always the same size and the lower-left corner, nor any other window edge, supports dragging to resize the window.  This makes navigating multiple content columns rather clunky. Tested on Intel macOS Ventura 13.2 (22D49).

**Comment by kroucis** [comment]
Strangely, I loaded up Lume today and now resizing using the window corners works just fine. I'm not sure what happened but my initial experience yesterday did not allow resizing.

**Comment by reyamir** [comment]
ah, in Splash Screen and Welcome screen (with Login and Create button), it set to not resizable
but main app screen is resizable
