### ISSUE TITLE
Window is transparent on Linux

### ISSUE THREAD

**Issue by stpnwf** [lumehq/lume#77]
Was there supposed to be blur here instead of transparency? Kinda hard to read stuff...

OS: Fedora 38
Lume v1.2.0-beta AppImage

![Screenshot from 2023-08-27 12-17-05](https://github.com/luminous-devs/lume/assets/81482539/eb7023b7-1cce-418e-8b8f-19f7f64b5005)

**Comment by reyamir** [comment]
oh, look like Linux doesn't support vibrancy (or mica) effect, I'll find other way to make it same as macOS or Windows
