### ISSUE TITLE
Support direct messages

### ISSUE THREAD

**Issue by reyamir** [lumehq/lume#8]

**Comment by cbeams** [comment]
I see this issue is resolved, but having just installed Lume on macOS and looked around quite a bit, I cannot find any support for DMs at all. Am I missing something?

**Comment by reyamir** [comment]
Hi, thank you for trying Lume.
In Lume v4, direct message is not support yet. But I still consider between dedicate chat-focused app or embed inside Lume.

**Comment by reyamir** [comment]
Ah, besides the direct message feature, would you mind providing feedback about some other aspects?

Despite releasing a new version, I haven't announced it yet because I'm still collecting feedback and continuing to improve it to reach a perfect state.

**Comment by reyamir** [comment]
Thank you for your valuable feedback. The new version will be coming this week. I'm happy to invite you to try it again.

**Comment by cbeams** [comment]
Great, thanks. If you mention the release here, I'll be sure to see it, cheers!

**Comment by reyamir** [comment]
Hi @cbeams , Lume v4 is ready to use on macOS, you can it here: https://github.com/lumehq/lume/releases/tag/v4.0.5

**Comment by cbeams** [comment]
Thanks, @reyamir. I've downloaded it (4.0.7 now) and will try it out.
