### ISSUE TITLE
Onboarding Review

### ISSUE THREAD

**Issue by karnagebitcoin** [lumehq/lume#85]
Hey hey! Here is my recording of the onboarding flow (I skipped the first 2 screens and probably should have added something there as well in hindsight):

https://cln.sh/HmGh0wT7

Happy to follow up with any questions you might have, or brainstorm further ideas.
Cheers!

**Comment by reyamir** [comment]
yo, thank you for doing review

Do you think Lume's onboarding flow is clear enough for both nostr users and non-nostr users? should any steps be added? 

One thing I'm considering is add a screen introduce about Nostr, and introduce about Lume features, before creating/import account step

**Comment by karnagebitcoin** [comment]
I pointed out in the video that some steps might be too confusing for non-nostr users. For example, relays. 
Learning about nostr would be great, but I am not sure if it should be done via onboarding. I think a UX where the user can access an additional learning area on their own once onboarded would be less pushy and less intimidating. I imagine it as a progress bar with number of steps completed 

2/6
-----------

with a title similar to "Become a nostr ninja" or "master nostr" 

The idea is to let them visit a central repository of steps that educate the user about various concepts such as relays, zaps, other apps. As the user completes each step (perhaps go through another intro flow for each concept), they fill in the progress bar and at the end get some sort of an exclusive badge. I haven't explored this in much detail yet just some rough ideas.

**Comment by karnagebitcoin** [comment]
quick and dirty idea:

<img width="573" alt="CleanShot 2023-09-11 at 10 45 55@2x" src="https://github.com/luminous-devs/lume/assets/131526701/684a1cfc-77e6-4a68-b340-1c291154c55f">

**Comment by karnagebitcoin** [comment]
another. The idea here would be to show progress as they learn about concepts, introduce rewards (well designed exclusive badges granted by Lume), guided flows for each concept, and interactive steps to add relays, explore wallet options etc...

<img width="437" alt="CleanShot 2023-09-11 at 10 55 33@2x" src="https://github.com/luminous-devs/lume/assets/131526701/4f6636b0-a339-4c47-bb56-656ea0b80a7b">

**Comment by reyamir** [comment]
I'm really like this idea, it can be part of lume widget too

![Frame 12](https://github.com/luminous-devs/lume/assets/123083837/220fda9f-8fb2-4796-abb4-2ff995f787fd)

**Comment by karnagebitcoin** [comment]
yeah for sure! just design it better than my placeholder lol

**Comment by fmaul** [comment]
Great review @karnagebitcoin  ... what I was thinking about the tag suggestions: It would make sense to group multiple tags into topics, e.g.
- Food (#food, #breakfast, #foodstr) 
- Gardening (#gardening #gardenstr #harvestr)
....

Then users wouldn't need to know some of the obscure tags we use. Was thinking of doing something like this for slidestr as well.

**Comment by reyamir** [comment]
I wonder if there is an API to get trending hashtags and group them by category.
currently I add hashtag manually

**Comment by karnagebitcoin** [comment]
> Great review @karnagebitcoin ... what I was thinking about the tag suggestions: It would make sense to group multiple tags into topics, e.g.
> 
> * Food (#food, #breakfast, #foodstr)
> * Gardening (#gardening #gardenstr #harvestr)
>   ....
> 
> Then users wouldn't need to know some of the obscure tags we use. Was thinking of doing something like this for slidestr as well.

Yes, this would be ideal. We need to actually move away from hashtags IMO because it's too easy to forget to tag things and sometimes people spam them to try to gain more attention to their junk.

What we need is some sort of evil algo that looks at a key phrase like "pancake breakfast" and associates that with food topic, but also looks at the entire note to make sure it's actually talking about food and not how some world leader was assassinated while eating his pancake breakfast... you get the idea. 

But as an interim step, perhaps just grouping hashtags would be a good step.

**Comment by karnagebitcoin** [comment]
> I wonder if there is an API to get trending hashtags and group them by category. currently I add hashtag manually

Maybe check out nostr.band or talk to Brugman about it? I am sure he could develop something, dude is a genius.
