### ISSUE TITLE
Database Error on First Open

### ISSUE THREAD

**Issue by zyrotin** [lumehq/lume#86]
Hi,
Tried installing 1.2.4 and it stalled out with database errors. I'm attaching the screen shots.
Running MacOS 13.5.2 on Macbook Air M2

<img width="400" alt="Screenshot 2023-09-12 at 6 13 49 PM" src="https://github.com/luminous-devs/lume/assets/6876060/0ee6b379-38fb-45be-a916-201b134d28dc">
<img width="526" alt="Screenshot 2023-09-12 at 6 14 37 PM" src="https://github.com/luminous-devs/lume/assets/6876060/bbd1d321-76b6-4cb5-8daa-914f47bcde35">
<img width="401" alt="Screenshot 2023-09-12 at 6 15 08 PM" src="https://github.com/luminous-devs/lume/assets/6876060/7135f249-a9e8-499b-86df-9a80af82f322">

**Comment by reyamir** [comment]
thank you for detail report, I'll checking it, look like something wrong with sqlite migration script (last_login_at) cannot be added

you can try fix it by delete local data in this path `"/Users/<user name>/Library/Application Support/com.lume.nu/"`, then restart app

**Comment by zyrotin** [comment]
That fixed it. I tested Lume a while back, maybe there was something in there that conflicted?

**Comment by reyamir** [comment]
hmm, look like after update to new version, sqlite migration isn't run yet, I will look into this case

**Comment by thetronjohnson** [comment]
@reyamir I'm facing this same issue too

**Comment by reyamir** [comment]
oh, if you get this issue, you can fix by delete all data in folder "/Users/<user name>/Library/Application Support/com.lume.nu/"

but I will find a way to solve this issue without delete old data
