### ISSUE TITLE
libthai.so.0 shared library error when launching v1.2.4 appimage

### ISSUE THREAD

**Issue by sysfu** [lumehq/lume#88]
Environment: gentoo linux
error: `lume: error while loading shared libraries: libthai.so.0: cannot open shared object file: No such file or directory`

**Comment by reyamir** [comment]
look like tauri AppImage problem https://github.com/tauri-apps/tauri/issues/4930

I will try generate flatpak instead

**Comment by sysfu** [comment]
> look like tauri AppImage problem [tauri-apps/tauri#4930](https://github.com/tauri-apps/tauri/issues/4930)
> 
> I will try generate flatpak instead

Did you have any success generating a flatpak?  I could not fine a flatpak version of lume on the latest releases page, or in flathub.org.
