### ISSUE TITLE
Cannot read properties of null (reading map)

### ISSUE THREAD

**Issue by netwarp** [lumehq/lume#90]
app version 1.2.4
plateform win32

**Comment by reyamir** [comment]
Hi, can you help me test again with v1.2.5 https://github.com/luminous-devs/lume/releases/tag/v1.2.5

**Comment by netwarp** [comment]
![lume_database](https://github.com/luminous-devs/lume/assets/8652937/6c7566b7-e959-4828-811f-baee25bdea30)

**Comment by reyamir** [comment]
oh, I will check it
