### ISSUE TITLE
Can't resize window

### ISSUE THREAD

**Issue by patrickjohncollins** [lumehq/lume#92]
Just installed Lume on Windows.  I can't resize the window or maximize.  Any idea why?  I'm a dev, would be happy to work on a fix if you can point me in the right direction.

**Comment by reyamir** [comment]
oh, thank you. Let me test it first, last time I check it still work on Windows
can you share me which screen you cannot resize?, maybe it only affect with certain screen,

**Comment by patrickjohncollins** [comment]
What do you mean by "which screen you cannot resize?"  I can't resize the Lume app window, unlike any other app I have installed on Windows.  If I move the mouse cursor to the edge of the Lume app window, there is no arrow-resize cursor.  Also the maximize button is disabled.  Is there some "Allow Resize" setting that has been set to "false"?  Thanks!

**Comment by reyamir** [comment]
yo, I've found a issue and it is fixed in this commit https://github.com/luminous-devs/lume/pull/91/commits/74ff49b8db7957cd4efb4264165a222b848ae819

new version will be release in this week

**Comment by reyamir** [comment]
If you want to test before release, you can run from source in this branch https://github.com/luminous-devs/lume/tree/feat/ui-patch

Install packages
```
pnpm install
```

Run dev build
```
pnpm tauri dev
```

**Comment by patrickjohncollins** [comment]
Nice!  

While I have you here, does this app auto-update?  

Also... is there any reason why the app window is first set to 400x500, then subsequently set to 1080x800 ?

  async function setWindow() {
    await appWindow.setSize(new LogicalSize(400, 500));
    await appWindow.setResizable(false);
    await appWindow.center();
  }

  async function resetWindow() {
    await appWindow.setSize(new LogicalSize(1080, 800));
    await appWindow.setResizable(true);
    await appWindow.center();
  }

  useEffect(() => {
    setWindow();

    return () => {
      resetWindow();
    };
  }, []);

**Comment by reyamir** [comment]
Yes, Lume have auto-update
I add screen resize in this step just only for aesthetic purpose only (from Welcome Screen -> Login/Create screen). But it seem dump, cause a bit confused for user, I will redesign it in the next update
