### ISSUE TITLE
unexpected error after every start

### ISSUE THREAD

**Issue by arneschween** [lumehq/lume#93]
was just exploring the new version 1.2.6 a bit, suddenly that and it stays with every restart. Only the report issue on github button works.

![2023-10-01 14_50_00-Lume](https://github.com/luminous-devs/lume/assets/5214548/52e564ae-e480-416e-a716-605ab3673481)

**Comment by reyamir** [comment]
Oh seem strange error, it didn't get this error on windows 11, let me test with windows 10

**Comment by tensor5g** [comment]
I also crash on start, my error looks a little different though

![image](https://github.com/luminous-devs/lume/assets/74799905/a8800c78-4fc2-449d-bd3d-9bf11c2b83ab)

Windows 11 23H2

**Comment by reyamir** [comment]
Hi, v2.1.0 is not official release yet, still use for testing only, you can download v2.0.1 instead https://github.com/luminous-devs/lume/releases/tag/v2.0.1

or you can wait for v2.1.0 fully released, maybe in the weekend
