### ISSUE TITLE
[BUG] Opening a Chat - Unexpected Error

### ISSUE THREAD

**Issue by crimsonleaf363** [lumehq/lume#97]
### **Error**
"undefined is not an object (evaluating 'o.length')"

### **Problem**
An unexpected error occurs when I attempt to open a chat.

### **To Reproduce**
1. Go to 'Chat'
2. Select a chat
3. See error

### **Expected behavior**
The chat opens successfully after the user selects it.

### **Device**
 - Apple M2
 - Platform: darwin 14.0.0
 - App Version 1.2.7

**Comment by reyamir** [comment]
Hi, thank for your report, I've fixed this issue in v2, it will be released in this Thursday
