### ISSUE TITLE
react not defined

### ISSUE THREAD

**Issue by lastdof** [lumehq/lume#99]
It worked one minute though :) 

![Capture d'écran 2023-10-26 164236](https://github.com/luminous-devs/lume/assets/4004560/f3de61ff-f9bc-4e52-9dd0-c9c0390ed01e)

**Comment by reyamir** [comment]
Hi, can you try again with latest ver here: https://github.com/luminous-devs/lume/releases/tag/v2.0.0
I forgot update download link in website 😅
